### ISSUE TITLE
Hello, can i get iframe crunchyroll

### ISSUE THREAD

**Issue by huutai97** [Mssjim/crunchyroll.js#1]
https://static.crunchyroll.com/vilos-v2/web/vilos/player.html
I use your package, can i get iframe player ?

**Comment by Mssjim** [comment]
I believe it's not possible 😫
But, getting the `episode object`, you will get `links/streams` with a "temporary" link with the m3u8 addresses of streams.
Something like:
```txt
#EXT-X-STREAM-INF:BANDWIDTH=8126877,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
https://pl.crunchyroll.com/evs3/b8f882125bc2e5f23701f654d4c03a39/assets/e655b0dabea7cdf181cfa709db5e3636_4887524.mp4/index-v1-a1.m3u8?res=1920x1080&Expires=1675649232&....
```

Then using a supported player (such as video.js with the HLS extension) you will be able to play them. However, it is something very complicated to do, and requires knowledge about refresh_tokens and the like, given that crunchyroll comes day after day creating barriers to make it difficult to access these links due to piracy.

**Comment by codsec** [comment]
> I believe it's not possible 😫 But, getting the `episode object`, you will get `links/streams` with a "temporary" link with the m3u8 addresses of streams. Something like:
> 
> ```
> #EXT-X-STREAM-INF:BANDWIDTH=8126877,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
> https://pl.crunchyroll.com/evs3/b8f882125bc2e5f23701f654d4c03a39/assets/e655b0dabea7cdf181cfa709db5e3636_4887524.mp4/index-v1-a1.m3u8?res=1920x1080&Expires=1675649232&....
> ```
> 
> Then using a supported player (such as video.js with the HLS extension) you will be able to play them. However, it is something very complicated to do, and requires knowledge about refresh_tokens and the like, given that crunchyroll comes day after day creating barriers to make it difficult to access these links due to piracy.

Hi @Mssjim u still want to work on this? if yes i have a suggestion can we talk on discord? my user on discord is @codsec
